Dependency checks updated, documentation updated for v1.2.1

diff --git a/src/somatypus b/src/somatypus
--- a/src/somatypus
+++ b/src/somatypus
@@ -483,6 +483,14 @@ merge_filter_all() {
 ################################### END OF FUNCTIONS ####################################
 
 
+# Check that dependencies (Platypus, tabix, bgzip, vcf-sort, Somatypus scripts) are installed
+hash Platypus.py 2>/dev/null || { echo -e "\nERROR: Platypus.py: command not found. Please install Platypus and add its directory to your PATH.\n" >&2; exit 1; }    
+hash tabix 2>/dev/null || { echo -e "\nERROR: tabix: command not found. Please install the SAMtools tabix package and add its directory to your PATH.\n" >&2; exit 1; }    
+hash bgzip 2>/dev/null || { echo -e "\nERROR: bgzip: command not found. Please install the SAMtools tabix package and add its directory to your PATH.\n" >&2; exit 1; }    
+hash vcf-sort 2>/dev/null || { echo -e "\nERROR: vcf-sort: command not found. Please install VCFtools and add its directory to your PATH.\n" >&2; exit 1; }    
+hash Somatypus_SplitMA-MNVs.py 2>/dev/null || { echo -e "\nERROR: Somatypus directory not included in the PATH. Please add the somatypus/src directory to your PATH.\n" >&2; exit 1; }    
+
+
 
 # If no arguments (or -h): print help
 if [ "$#" -eq 0 ]; then
@@ -601,13 +609,6 @@ for FILE in `ls $BAMSDIR/*.bam`; do
     fi
 done
 
-
-# Check that dependencies (Platypus, tabix, bgzip, vcf-sort, Somatypus scripts) are installed
-hash Platypus.py 2>/dev/null || { echo -e "\nERROR: Platypus.py: command not found. Please install Platypus and add its directory to your PATH.\n" >&2; exit 1; }    
-hash tabix 2>/dev/null || { echo -e "\nERROR: tabix: command not found. Please install the SAMtools tabix package and add its directory to your PATH.\n" >&2; exit 1; }    
-hash bgzip 2>/dev/null || { echo -e "\nERROR: bgzip: command not found. Please install the SAMtools tabix package and add its directory to your PATH.\n" >&2; exit 1; }    
-hash vcf-sort 2>/dev/null || { echo -e "\nERROR: vcf-sort: command not found. Please install VCFtools and add its directory to your PATH.\n" >&2; exit 1; }    
-hash Somatypus_SplitMA-MNVs.py 2>/dev/null || { echo -e "\nERROR: Somatypus directory not included in the PATH. Please add the somatypus/src directory to your PATH.\n" >&2; exit 1; }    
 
 
 # START RUNNING
